import { TextType } from "./types";

export const text: TextType = {
  noConnection: {
    ua: "Немає мережі",
    ru: "Нет сети",
    eng: "Settings",
    pl: "Brak sieci",
  },
  changeLanguage: {
    ua: "Змінити мову",
    ru: "Сменить язык",
    eng: "Change language",
    pl: "Zmień język",
  },
  settings: {
    ua: "Налаштування",
    ru: "Настройки",
    eng: "Settings",
    pl: "Ustawienia",
  },
  mainCurrency: {
    ua: "Основна валюта",
    ru: "Основная валюта",
    eng: "Main currency",
    pl: "Główna waluta",
  },
  selectFirstPrimaryCurrency: {
    ua: "Виберіть основну валюту",
    ru: "Выберите основную валюту",
    eng: "Select the primary currency",
    pl: "Wybierz walutę główną",
  },
  selectPrimaryCurrency: {
    ua: "Спочатку виберіть основну валюту в налаштуваннях",
    ru: "Сначала выберите основную валюту в настройках",
    eng: "First, select the primary currency in settings",
    pl: "Najpierw wybierz walutę główną w ustawieniach",
  },
  currentRate: {
    ua: "Актуальний курс",
    ru: "Актуальный курс",
    eng: "Current rate",
    pl: "Aktualny kurs",
  },
  appData: {
    ua: "Дані застосунку",
    ru: "Данные приложения",
    eng: "App data",
    pl: "Dane aplikacji",
  },
  deleteAll: {
    ua: "Видалити все",
    ru: "Удалить всё",
    eng: "Delete all",
    pl: "Usuń wszystko",
  },
  sync: {
    ua: "Синхронізація",
    ru: "Синхронизация",
    eng: "Synchronization",
    pl: "Synchronizacja",
  },
  restoreData: {
    ua: "Відновити? Поточні дані будуть видалені!",
    ru: "Восстановить? Текущие данные будут удалены!",
    eng: "Restore? Current data will be deleted!",
    pl: "Przywrócić? Aktualne dane zostaną usunięte!",
  },
  loaded: {
    ua: "Завантажено",
    ru: "Загружено",
    eng: "Loaded",
    pl: "Załadowano",
  },
  dataDeleted: {
    ua: "Дані на сервері видалено",
    ru: "Данные на сервере удалены",
    eng: "Data on the server has been deleted",
    pl: "Dane na serwerze zostały usunięte",
  },
  darkTheme: {
    ua: "Темна тема",
    ru: "Темная тема",
    eng: "Dark theme",
    pl: "Ciemny motyw",
  },
  save: {
    ua: "Зберегти",
    ru: "Сохранить",
    eng: "Save",
    pl: "Zapisz",
  },
  confirmDeleteAll: {
    ua: "Ви дійсно хочете видалити все?",
    ru: "Вы действительно хотите удалить всё?",
    eng: "Do you really want to delete everything?",
    pl: "Czy na pewno chcesz usunąć wszystko?",
  },
  confirm: {
    ua: "Підтвердити",
    ru: "Подтвердить",
    eng: "Confirm",
    pl: "Potwierdź",
  },

  cancel: {
    ua: "Скасувати",
    ru: "Отменить",
    eng: "Cancel",
    pl: "Anuluj",
  },
  enterPassword: {
    ua: "Введіть пароль",
    ru: "Введите пароль",
    eng: "Enter password",
    pl: "Wprowadź hasło",
  },
  restore: {
    ua: "Відновити",
    ru: "Восстановить",
    eng: "Restore",
    pl: "Przywróć",
  },
  backup: {
    ua: "Зробити резервну копію",
    ru: "Сделать резервную копию",
    eng: "Backup",
    pl: "Utwórz kopię zapasową",
  },
  success: {
    ua: "Успішно",
    ru: "Успешно",
    eng: "Success",
    pl: "Sukces",
  },
  error: {
    ua: "Помилка",
    ru: "Ошибка",
    eng: "Error",
    pl: "Błąd",
  },
  loading: {
    ua: "Завантаження",
    ru: "Загрузка",
    eng: "Loading",
    pl: "Ładowanie",
  },
  changeMainCurrency: {
    ua: "Зміна основної валюти",
    ru: "Изменение основной валюты",
    eng: "Changing main currency",
    pl: "Zmiana głównej waluty",
  },
  confirmChangeMainCurrency: {
    ua: "Ви дійсно хочете змінити основну валюту? Курси решти валют потрібно буде налаштувати заново!",
    ru: "Вы действительно хотите изменить основную валюту? Курсы оставшихся валют нужно будет настроить заново!",
    eng: "Do you really want to change the main currency? The rates of the remaining currencies will need to be reset!",
    pl: "Czy na pewno chcesz zmienić główną walutę? Kursy pozostałych walut trzeba będzie skonfigurować od nowa!",
  },
  balance: {
    ua: "Баланс",
    ru: "Баланс",
    eng: "Balance",
    pl: "Saldo",
  },
  budget: {
    ua: "Бюджет",
    ru: "Бюджет",
    eng: "Budget",
    pl: "Budżet",
  },
  selectCurrencyAndAddAccounts: {
    ua: "Спочатку виберіть валюту та додайте рахунки",
    ru: "Сначала выберите валюту и добавьте счета",
    eng: "First, select the currency and add accounts",
    pl: "Najpierw wybierz walutę i dodaj konta",
  },
  monthlyExpenses: {
    ua: "Сума витрат за місяць",
    ru: "Сумма расходов на месяц",
    eng: "Monthly expenses",
    pl: "Miesięczne wydatki",
  },
  account: {
    ua: "Рахунок",
    ru: "Счёт",
    eng: "Account",
    pl: "Konto",
  },
  selectDate: {
    ua: "Вибір дати",
    ru: "Выбор даты",
    eng: "Select date",
    pl: "Wybór daty",
  },
  accounts: {
    ua: "Рахунки",
    ru: "Счета",
    eng: "Accounts",
    pl: "Konta",
  },
  addAccount: {
    ua: "Додати рахунок",
    ru: "Добавить счет",
    eng: "Add account",
    pl: "Dodaj konto",
  },
  enterPlannedAmount: {
    ua: "Введіть плановану суму",
    ru: "Введите планируемую сумму",
    eng: "Enter the planned amount",
    pl: "Wprowadź planowaną kwotę",
  },
  addFirstAccount: {
    ua: "Додайте перший рахунок",
    ru: "Добавьте первый счет",
    eng: "Add the first account",
    pl: "Dodaj pierwsze konto",
  },
  accountName: {
    ua: "Назва рахунку",
    ru: "Название счета",
    eng: "Account name",
    pl: "Nazwa konta",
  },
  name: {
    ua: "Назва",
    ru: "Название",
    eng: "Name",
    pl: "Nazwa",
  },
  amount: {
    ua: "Сума",
    ru: "Сумма",
    eng: "Amount",
    pl: "Kwota",
  },
  initialBalance: {
    ua: "Початковий баланс",
    ru: "Начальный баланс",
    eng: "Initial balance",
    pl: "Saldo początkowe",
  },
  accountCurrency: {
    ua: "Валюта рахунку",
    ru: "Валюта счёта",
    eng: "Account currency",
    pl: "Waluta konta",
  },
  color: {
    ua: "Колір",
    ru: "Цвет",
    eng: "Color",
    pl: "Kolor",
  },
  edit: {
    ua: "Змінити",
    ru: "Изменить",
    eng: "Edit",
    pl: "Edytuj",
  },
  delete: {
    ua: "Видалити",
    ru: "Удалить",
    eng: "Delete",
    pl: "Usuń",
  },
  accountDeletion: {
    ua: "Видалення рахунку",
    ru: "Удаление счёта",
    eng: "Account deletion",
    pl: "Usunięcie konta",
  },
  confirmAccountDeletion: {
    ua: "Ви дійсно хочете видалити рахунок?",
    ru: "Вы действительно хотите удалить счёт?",
    eng: "Do you really want to delete the account?",
    pl: "Czy na pewno chcesz usunąć konto?",
  },
  incomes: {
    ua: "Доходи",
    ru: "Доходы",
    eng: "Incomes",
    pl: "Przychody",
  },
  expenses: {
    ua: "Витрати",
    ru: "Расходы",
    eng: "Expenses",
    pl: "Wydatki",
  },
  transactions: {
    ua: "Транзакції",
    ru: "Транзакции",
    eng: "Transactions",
    pl: "Transakcje",
  },

  noTansactions: {
    ua: "Транзакції відсутні",
    ru: "Транзакции отсутствуют",
    eng: "No transactions",
    pl: "Brak transakcji",
  },
  filter: {
    ua: "Фільтр",
    ru: "Фильтр",
    eng: "Filter",
    pl: "Filtr",
  },
  byDate: {
    ua: "За датою",
    ru: "По дате",
    eng: "By date",
    pl: "Według daty",
  },
  all: {
    ua: "Усі",
    ru: "Все",
    eng: "All",
    pl: "Wszystkie",
  },
  today: {
    ua: "Сьогодні",
    ru: "Сегодня",
    eng: "Today",
    pl: "Dzisiaj",
  },
  month: {
    ua: "Місяць",
    ru: "Месяц",
    eng: "Month",
    pl: "Miesiąc",
  },
  year: {
    ua: "Рік",
    ru: "Год",
    eng: "Year",
    pl: "Rok",
  },
  byTransactionType: {
    ua: "За типом транзакції",
    ru: "По типу транзакции",
    eng: "By transaction type",
    pl: "Według rodzaju transakcji",
  },
  addExpense: {
    ua: "Додати витрату",
    ru: "Внести расход",
    eng: "Add expense",
    pl: "Dodaj wydatek",
  },
  addIncome: {
    ua: "Додати дохід",
    ru: "Внести доход",
    eng: "Add income",
    pl: "Dodaj przychód",
  },
  selectAccount: {
    ua: "Виберіть рахунок",
    ru: "Выберите счёт",
    eng: "Select account",
    pl: "Wybierz konto",
  },
  category: {
    ua: "Категорія",
    ru: "Категория",
    eng: "Category",
    pl: "Kategoria",
  },
  incomeCategories: {
    ua: "Категорії доходів",
    ru: "Категории доходов",
    eng: "Income categories",
    pl: "Kategorie dochodów",
  },
  expenseCategories: {
    ua: "Категорії витрат",
    ru: "Категории расходов",
    eng: "Expense categories",
    pl: "Kategorie wydatków",
  },
  description: {
    ua: "Опис",
    ru: "Описание",
    eng: "Description",
    pl: "Opis",
  },
  set: {
    ua: "Встановити",
    ru: "Установить",
    eng: "Set",
    pl: "Ustawić",
  },
  confirmTransactionDeletion: {
    ua: "Ви дійсно хочете видалити транзакцію?",
    ru: "Вы действительно хотите удалить транзакцию?",
    eng: "Do you really want to delete the transaction?",
    pl: "Czy na pewno chcesz usunąć transakcję?",
  },
  transactionDeletion: {
    ua: "Видалення транзакції",
    ru: "Удаление транзакции",
    eng: "Transaction deletion",
    pl: "Usunięcie transakcji",
  },
};
